name: hsfm
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - xmltodict
  - pip
  - gdal
  - scipy
  - haversine
  - utm
  - panel
  - holoviews
  - geoviews
  - seaborn
  - menpo::opencv
  - rasterstats
  - pip:
    - elevation
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"
